version: '3.9'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'qwerty'
      POSTGRES_DB: 'postgres'
    ports:
      - "5432:5432"
  app:
    depends_on:
      - postgres
    build: ./
    command: ./app
    environment:
      - PG_PASSWORD=${PG_PASSWORD:?database password not set}
    ports:
      - "8000:8000"