version: '3.9'

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=${PG_USER:?username not set}
      - POSTGRES_PASSWORD=${PG_PASSWORD:?db password not set}
      - POSTGRES_DB=${PG_DB:?db name not set}
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 5s
      timeout: 5s
      retries: 5

  migrate:
    image: migrate/migrate
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - PG_URL=${PG_URL:?db url not set}
    volumes:
      - ./db/migrations:/migrations
    command: -database "$PG_URL" -path migrations up

  app:
    depends_on:
      postgres:
        condition: service_healthy
    build: ./
    command: ./app
    environment:
      - PG_PASSWORD=${PG_PASSWORD:?db password not set}
    ports:
      - "8000:8000"