version: '3.9'

services:
  postgres:
    image: postgres
    volumes:
      - ./pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'qwerty'
      POSTGRES_DB: 'postgres'
    ports:
      - "5432:5432"